language: python
python:
    - "3.4"
env:
    - DJANGO=1.9.7 DB=mysql
install:
    - pip install -r requirements.txt
    - pip install PyMySQL
    - pip install coveralls
script:
    - python manage.py test api
    - coverage run --source=api manage.py test api
after_success: coveralls
