language: python
python:
    - "3.4"
env:
    - DJANGO=1.9.7 DB=mysql
install:
    - pip install -r requirements.txt
    - pip install PyMySQL
    - pip install coveralls
script:
    - python manage.py test --settings=api.test_settings api
    - coverage run --source=api manage.py --settings=api.test_settings test api
after_success: coveralls
