language: python
python:
    - "3.4"
env:
    - DJANGO=1.9.7 DB=mysql
install:
    - pip install -r requirements.txt
    - pip install PyMySQL
    - pip install coveralls
    - pip install djangorestframework==3.3.3
    - pip install django-rest-swagger==0.3.8
script:
    - python manage.py test --settings=api.test_settings api
    - coverage run --source=api manage.py test --settings=api.test_settings api
after_success: coveralls
