# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=50)),
                ('line_2', models.CharField(max_length=50)),
                ('line_3', models.CharField(max_length=50)),
                ('line_4', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='AppNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('body', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('max_app_version', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'app_news',
            },
        ),
        migrations.CreateModel(
            name='AppVersions',
            fields=[
                ('app_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('app_version_code', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'app_versions',
            },
        ),
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('mil', models.IntegerField()),
                ('top', models.CharField(max_length=6)),
            ],
            options={
                'managed': False,
                'db_table': 'Bags',
            },
        ),
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefield', models.DateField()),
                ('year', models.SmallIntegerField()),
                ('month', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('day_of_year', models.SmallIntegerField()),
                ('day_of_month', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.IntegerField()),
                ('note', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'changelog',
            },
        ),
        migrations.CreateModel(
            name='CiSessions',
            fields=[
                ('session_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('last_activity', models.IntegerField()),
                ('user_agent', models.CharField(max_length=120)),
                ('user_data', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'ci_sessions',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vmi', models.IntegerField()),
                ('homepage', models.CharField(db_column='homePage', max_length=50)),
                ('address', models.CharField(blank=True, max_length=75, null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.IntegerField()),
                ('first', models.IntegerField()),
                ('title', models.IntegerField()),
                ('email', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('fax', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='FileCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'managed': False,
                'db_table': 'file_categories',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(db_column='fileType', max_length=10)),
                ('views', models.IntegerField()),
                ('addtime', models.DateTimeField(db_column='addTime')),
                ('filename', models.CharField(blank=True, db_column='fileName', max_length=60, null=True)),
                ('origname', models.CharField(blank=True, db_column='origName', max_length=60, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'file_types',
            },
        ),
        migrations.CreateModel(
            name='Finishes',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('company', models.IntegerField()),
                ('description', models.TextField()),
                ('baseprice', models.SmallIntegerField()),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'finishes',
            },
        ),
        migrations.CreateModel(
            name='InProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.IntegerField()),
                ('total_qty', models.IntegerField()),
                ('complete', models.IntegerField()),
                ('rec_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'in_process',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=50, unique=True)),
                ('live_inv', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemAliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'item_aliases',
            },
        ),
        migrations.CreateModel(
            name='ItemReceipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.DateField()),
                ('qty', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'item_receipts',
            },
        ),
        migrations.CreateModel(
            name='ItemReceiptTypes',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'item_receipt_types',
            },
        ),
        migrations.CreateModel(
            name='ItemReqLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('need_date', models.DateField()),
                ('job', models.CharField(max_length=25)),
                ('issued', models.IntegerField()),
                ('whse', models.CharField(db_column='Whse', max_length=25)),
            ],
            options={
                'managed': False,
                'db_table': 'item_req_lines',
            },
        ),
        migrations.CreateModel(
            name='ItemReqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'item_reqs',
            },
        ),
        migrations.CreateModel(
            name='ItemRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('eff_date', models.DateField()),
                ('live_inv', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'item_revisions',
            },
        ),
        migrations.CreateModel(
            name='ItemSpecialInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'item_special_instructions',
            },
        ),
        migrations.CreateModel(
            name='ItemTransitionRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'item_transition_rules',
            },
        ),
        migrations.CreateModel(
            name='Kitparts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partqty', models.IntegerField(db_column='PartQty')),
            ],
            options={
                'managed': False,
                'db_table': 'kitparts',
            },
        ),
        migrations.CreateModel(
            name='Kits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitname', models.CharField(db_column='KitName', max_length=50)),
                ('bagtype', models.IntegerField(db_column='BagType')),
                ('boxtype', models.SmallIntegerField(db_column='BoxType')),
                ('ctnqty', models.IntegerField(db_column='CtnQty')),
            ],
            options={
                'managed': False,
                'db_table': 'kits',
            },
        ),
        migrations.CreateModel(
            name='MatReqLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=25)),
                ('issued', models.IntegerField()),
                ('job_qty', models.IntegerField()),
                ('need_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'mat_req_lines',
            },
        ),
        migrations.CreateModel(
            name='MatReqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'mat_reqs',
            },
        ),
        migrations.CreateModel(
            name='MonthNames',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'managed': False,
                'db_table': 'month_names',
            },
        ),
        migrations.CreateModel(
            name='NCiSessions',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('timestamp', models.IntegerField()),
                ('data', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'n_ci_sessions',
            },
        ),
        migrations.CreateModel(
            name='OldOrderlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ol_id', models.IntegerField()),
                ('partnum', models.CharField(db_column='partNum', max_length=50)),
                ('item_id', models.IntegerField()),
                ('item_rev', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('duedate', models.DateField(db_column='dueDate')),
                ('shipdate', models.DateField(blank=True, db_column='shipDate', null=True)),
                ('status', models.IntegerField()),
                ('chg_date', models.DateTimeField()),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'old_orderlines',
            },
        ),
        migrations.CreateModel(
            name='OrderlineNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'orderline_notes',
            },
        ),
        migrations.CreateModel(
            name='Orderlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('duedate', models.DateField(db_column='dueDate')),
                ('shipdate', models.DateField(blank=True, db_column='shipDate', null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'orderlines',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custpo', models.CharField(db_column='custPo', max_length=40)),
                ('o_date', models.DateField(db_column='O_date')),
            ],
            options={
                'managed': False,
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'managed': False,
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(db_column='PartNumber', max_length=50)),
                ('partdesc', models.CharField(blank=True, db_column='PartDesc', max_length=100, null=True)),
                ('orderqty', models.IntegerField(db_column='orderQty')),
                ('size', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=20)),
                ('clot', models.CharField(blank=True, db_column='cLot', max_length=25, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'parts',
            },
        ),
        migrations.CreateModel(
            name='Partfinishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'PartFinishes',
            },
        ),
        migrations.CreateModel(
            name='PjItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('part_num', models.CharField(max_length=50)),
                ('item_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('lot', models.CharField(max_length=30)),
                ('label_type', models.CharField(max_length=5)),
                ('item_revision', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'pj_items',
            },
        ),
        migrations.CreateModel(
            name='Printjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'printjob',
            },
        ),
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'processes',
            },
        ),
        migrations.CreateModel(
            name='ProcessLabelJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'process_label_jobs',
            },
        ),
        migrations.CreateModel(
            name='ProcessLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_boxes', models.SmallIntegerField()),
                ('box_number', models.SmallIntegerField()),
                ('po_number', models.CharField(max_length=15)),
                ('process', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'process_labels',
            },
        ),
        migrations.CreateModel(
            name='ProductionQueue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_line_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'production_queue',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('complete', models.IntegerField()),
                ('ack_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'purchase_order_lines',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('terms', models.CharField(max_length=50)),
                ('ship', models.CharField(max_length=50)),
                ('old_po_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='RevisionLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.IntegerField()),
                ('version_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'revision_levels',
            },
        ),
        migrations.CreateModel(
            name='RevNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'rev_notes',
            },
        ),
        migrations.CreateModel(
            name='ShipmentParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('billed', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'shipment_parts',
            },
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbrv', models.CharField(max_length=7)),
            ],
            options={
                'managed': False,
                'db_table': 'uom',
            },
        ),
        migrations.CreateModel(
            name='UomConversions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'uom_conversions',
            },
        ),
        migrations.CreateModel(
            name='UomParents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'uom_parents',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(db_column='lastName', max_length=30)),
                ('firstname', models.CharField(db_column='firstName', max_length=30)),
                ('companyid', models.IntegerField(db_column='companyId')),
                ('accesslevel', models.IntegerField(db_column='accessLevel')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=24)),
                ('active', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='VmiInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_revision', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('last_checked', models.DateField()),
                ('location', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'vmi_inventory',
            },
        ),
        migrations.CreateModel(
            name='VmiLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(db_column='Part', max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'vmi_labels',
            },
        ),
        migrations.CreateModel(
            name='VmiLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'vmi_locations',
            },
        ),
    ]
